import { defineConfig } from "orval";

export default defineConfig({
  roborev: {
    input: "src/lib/api/roborev/openapi.yaml",
    output: {
      target: "src/lib/api/roborev/generated-next/client.ts",
      schemas: "src/lib/api/roborev/generated-next/models",
      clean: true,
      client: "fetch",
      mode: "split",
      override: {
        header: () => ["Generated by Orval. Do not edit manually."],
        fetch: { useRuntimeFetcher: true },
        operationName: (operation) => {
          if (!operation.operationId) throw new Error("Every API operation must have an operationId");
          return operation.operationId.replace(/-([a-z0-9])/g, (_: string, character: string) =>
            character.toUpperCase(),
          );
        },
      },
    },
  },
});
