package main

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.kenn.io/middleman/internal/agentactivity"
	"go.kenn.io/middleman/internal/workspace"
)

func TestAgentHookRunReceivesLifecyclePayload(t *testing.T) {
	require := require.New(t)
	stateDir := t.TempDir()
	workspace := t.TempDir()
	t.Setenv(agentactivity.RuntimeSessionKeyEnv, "runtime-1")
	payload, err := json.Marshal(map[string]string{
		"session_id": "agent-1", "cwd": workspace,
		"hook_event_name": "UserPromptSubmit",
	})
	require.NoError(err)

	require.NoError(runAgentHookCLI([]string{
		"run", "--state-dir", stateDir, "--source", "middleman-agent-activity",
	}, strings.NewReader(string(payload)), io.Discard))

	snapshot, ok := agentactivity.NewStore(stateDir).SnapshotForWorkspace(
		workspace, []string{"runtime-1"},
	)
	require.True(ok)
	assert.Equal(t, agentactivity.StateWorking, snapshot.State)
}

func TestAgentHookRunEmitsClaudeWorkspaceContextOnSessionStart(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)
	stateDir := t.TempDir()
	worktree := t.TempDir()
	t.Setenv(agentactivity.RuntimeSessionKeyEnv, "runtime-1")
	contextText := workspace.RenderAgentContext(workspace.AgentContext{
		WorkspaceID: "ws-1", SourceKind: workspace.AgentSourceKindPullRequest,
		Provider: "github", PlatformHost: "github.com",
		RepoOwner: "acme", RepoName: "widget", ItemNumber: 42,
	})
	require.NoError(os.WriteFile(
		filepath.Join(worktree, "CLAUDE.local.md"), []byte(contextText), 0o644,
	))
	payload, err := json.Marshal(map[string]string{
		"session_id": "agent-1", "cwd": worktree,
		"hook_event_name": "SessionStart",
	})
	require.NoError(err)
	var stdout bytes.Buffer

	require.NoError(runAgentHookCLI([]string{
		"run", "--agent", "claude", "--state-dir", stateDir,
		"--source", "middleman-agent-activity",
	}, strings.NewReader(string(payload)), &stdout))

	var output struct {
		HookSpecificOutput struct {
			HookEventName     string `json:"hookEventName"`
			AdditionalContext string `json:"additionalContext"`
		} `json:"hookSpecificOutput"`
	}
	require.NoError(json.Unmarshal(stdout.Bytes(), &output))
	assert.Equal("SessionStart", output.HookSpecificOutput.HookEventName)
	assert.Contains(output.HookSpecificOutput.AdditionalContext, "Workspace ID: ws-1")
	assert.Contains(output.HookSpecificOutput.AdditionalContext, "PR: #42")
	assert.NotContains(output.HookSpecificOutput.AdditionalContext, "<!-- generated by middleman")

	snapshot, ok := agentactivity.NewStore(stateDir).SnapshotForWorkspace(
		worktree, []string{"runtime-1"},
	)
	require.True(ok)
	assert.Equal(agentactivity.StateIdle, snapshot.State)
}

func TestAgentHookRunDoesNotExposeUserClaudeContextFile(t *testing.T) {
	require := require.New(t)
	worktree := t.TempDir()
	require.NoError(os.WriteFile(
		filepath.Join(worktree, "CLAUDE.local.md"), []byte("private user context\n"), 0o644,
	))
	payload, err := json.Marshal(map[string]string{
		"session_id": "agent-1", "cwd": worktree,
		"hook_event_name": "SessionStart",
	})
	require.NoError(err)
	var stdout bytes.Buffer

	require.NoError(runAgentHookCLI([]string{
		"run", "--agent", "claude", "--state-dir", t.TempDir(),
		"--source", "middleman-agent-activity",
	}, strings.NewReader(string(payload)), &stdout))

	assert.Empty(t, stdout.String())
}

func TestAgentHookInstallRejectsRelativeDataDirectory(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)
	dir := t.TempDir()
	configPath := filepath.Join(dir, "config.toml")
	require.NoError(os.WriteFile(configPath, []byte("data_dir = \"relative-data\"\n"), 0o600))
	configDir := filepath.Join(dir, "codex")
	t.Setenv("CODEX_HOME", configDir)

	err := runAgentHookInstall("install", []string{
		"--config", configPath,
		"--agent", "codex",
		"--binary", "/opt/middleman",
	}, io.Discard)

	require.Error(err)
	assert.Contains(err.Error(), "absolute data_dir")
	_, statErr := os.Stat(filepath.Join(configDir, "hooks.json"))
	assert.ErrorIs(statErr, os.ErrNotExist)
}
