package server

import (
	"bytes"
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gitcmd "go.kenn.io/kit/git/cmd"

	"go.kenn.io/middleman/internal/apiclient/generated"
	"go.kenn.io/middleman/internal/config"
	"go.kenn.io/middleman/internal/db"
	ghclient "go.kenn.io/middleman/internal/github"
	"go.kenn.io/middleman/internal/testutil/dbtest"
	"go.kenn.io/middleman/internal/workspace"
	"go.kenn.io/middleman/internal/workspace/localruntime"
)

func TestLaunchWorkspaceRuntimeSessionPreparesAgentContext(t *testing.T) {
	t.Parallel()
	assert := assert.New(t)
	require := require.New(t)
	d := dbtest.Open(t)
	worktree := initServerWorkspaceGitRepo(t)
	repoID := seedServerWorkspaceRepo(t, d)
	seedServerWorkspaceMR(t, d, repoID)

	ws := &db.Workspace{
		ID:              "ws-agent-context",
		Platform:        "github",
		PlatformHost:    "github.com",
		RepoOwner:       "acme",
		RepoName:        "widget",
		ItemType:        db.WorkspaceItemTypePullRequest,
		ItemNumber:      42,
		GitHeadRef:      "feature/widgets",
		WorkspaceBranch: "feature/widgets",
		WorktreePath:    worktree,
		TmuxSession:     "middleman-ws-agent-context",
		TerminalBackend: "tmux",
		Status:          "ready",
	}
	require.NoError(d.InsertWorkspace(t.Context(), ws))
	staleMarked := "<!-- generated by middleman; safe to delete; regenerated on agent launch -->\nstale\n"
	require.NoError(os.WriteFile(filepath.Join(worktree, "AGENTS.local.md"), []byte(staleMarked), 0o644))

	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, t.TempDir(), filepath.Join(t.TempDir(), "tmux-record"))
	runtime := localruntime.NewManager(localruntime.Options{
		Targets: []localruntime.LaunchTarget{
			{
				Key:       "codex",
				Label:     "Codex",
				Kind:      localruntime.LaunchTargetAgent,
				Command:   []string{"/bin/sh", "-c", "exit 0"},
				Available: true,
			},
			{
				Key:       string(localruntime.LaunchTargetShell),
				Label:     "tmux",
				Kind:      localruntime.LaunchTargetShell,
				Command:   []string{tmuxPath},
				Available: true,
			},
		},
		TmuxCommand:             []string{tmuxPath},
		WrapAgentSessionsInTmux: true,
	})
	server := &Server{
		db:         d,
		workspaces: workspace.NewManager(d, t.TempDir()),
		runtime:    runtime,
	}
	input := &launchWorkspaceRuntimeSessionInput{ID: ws.ID}
	input.Body.TargetKey = "codex"

	_, err := server.launchWorkspaceRuntimeSession(t.Context(), input)
	require.NoError(err)

	agentsLocal, err := os.ReadFile(filepath.Join(worktree, "AGENTS.local.md"))
	require.NoError(err)
	assert.Contains(string(agentsLocal), "Source kind: pull request")
	assert.Contains(string(agentsLocal), "PR: #42")
	assert.Contains(string(agentsLocal), "Launch context")
	assert.NotContains(string(agentsLocal), "stale")
	assert.NoFileExists(filepath.Join(worktree, "CLAUDE.local.md"))
	assertServerGitIgnored(t, worktree, "AGENTS.local.md")
	status := strings.TrimSpace(string(runServerWorkspaceTestGit(t, worktree, "status", "--porcelain")))
	assert.Empty(status)
}

func TestWorkspaceRuntimeLaunchWritesAgentContextE2E(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)
	dir := t.TempDir()
	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, dir, filepath.Join(dir, "tmux-record"))
	agentPath := filepath.Join(dir, "helper-agent")
	require.NoError(os.WriteFile(agentPath, []byte("#!/bin/sh\nexit 0\n"), 0o755))
	cfg := &config.Config{
		Agents: []config.Agent{{Key: "codex", Label: "Codex", Command: []string{agentPath}}},
		Tmux:   config.Tmux{Command: []string{tmuxPath}},
	}
	client, _, _, _, _ := setupTestServerWithWorkspacesServer(t, cfg)
	ctx := context.Background()
	ws := createReadyWorkspace(t, ctx, client)

	assert.NoFileExists(filepath.Join(ws.WorktreePath, "AGENTS.local.md"))

	resp, err := client.HTTP.LaunchWorkspaceRuntimeSessionWithResponse(
		ctx, ws.Id,
		generated.LaunchWorkspaceRuntimeSessionInputBody{TargetKey: "codex"},
	)
	require.NoError(err)
	require.Equal(http.StatusOK, resp.StatusCode())

	agentsLocal, err := os.ReadFile(filepath.Join(ws.WorktreePath, "AGENTS.local.md"))
	require.NoError(err)
	assert.Contains(string(agentsLocal), "Source kind: pull request")
	assert.Contains(string(agentsLocal), "Push branch:")
	assert.NotContains(string(agentsLocal), "Working branch")
	assert.NoFileExists(filepath.Join(ws.WorktreePath, "CLAUDE.local.md"))
	assertServerGitIgnored(t, ws.WorktreePath, "AGENTS.local.md")
	status := strings.TrimSpace(string(runServerWorkspaceTestGit(
		t, ws.WorktreePath, "status", "--porcelain",
	)))
	assert.Empty(status)
}

func TestWorkspaceRuntimeLaunchWritesIssueAndKataAgentContextE2E(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)
	dir := t.TempDir()
	database := dbtest.Open(t)
	syncer := ghclient.NewSyncer(nil, database, nil, nil, time.Minute, nil, nil)
	t.Cleanup(syncer.Stop)
	srv := New(
		database, syncer, nil, "/", nil,
		ServerOptions{
			WorktreeDir:                        filepath.Join(dir, "worktrees"),
			DisableWorkspaceBackgroundMonitors: true,
		},
	)
	t.Cleanup(func() { gracefulShutdown(t, srv) })
	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, dir, filepath.Join(dir, "tmux-record"))
	srv.runtime = localruntime.NewManager(localruntime.Options{
		Targets: []localruntime.LaunchTarget{
			{
				Key:       "codex",
				Label:     "Codex",
				Kind:      localruntime.LaunchTargetAgent,
				Command:   []string{"/bin/sh", "-c", "exit 0"},
				Available: true,
			},
			{
				Key:       string(localruntime.LaunchTargetShell),
				Label:     "tmux",
				Kind:      localruntime.LaunchTargetShell,
				Command:   []string{tmuxPath},
				Available: true,
			},
		},
		TmuxCommand:             []string{tmuxPath},
		WrapAgentSessionsInTmux: true,
	})

	issueWorktree := initServerWorkspaceGitRepo(t)
	seedIssue(t, database, "acme", "widget", 7, "open")
	require.NoError(database.InsertWorkspace(t.Context(), &db.Workspace{
		ID: "ws-issue-context", Platform: "github", PlatformHost: "github.com",
		RepoOwner: "acme", RepoName: "widget",
		ItemType: db.WorkspaceItemTypeIssue, ItemNumber: 7,
		GitHeadRef: "middleman/issue-7", WorkspaceBranch: "middleman/issue-7",
		WorktreePath: issueWorktree, Status: "ready",
	}))

	kataWorktree := initServerWorkspaceGitRepo(t)
	require.NoError(database.InsertWorkspace(t.Context(), &db.Workspace{
		ID: "ws-kata-context", Platform: "github", PlatformHost: "github.com",
		RepoOwner: "acme", RepoName: "widget",
		ItemType: db.WorkspaceItemTypeKataTask,
		ItemKey: db.KataWorkspaceItemKey(db.WorkspaceKataMetadata{
			DaemonID: "home", ProjectUID: "project-1", IssueUID: "issue-kata-1",
		}),
		GitHeadRef: "middleman/kata/task-123", WorkspaceBranch: "middleman/kata/task-123",
		WorktreePath: kataWorktree, Status: "ready",
		KataMetadata: &db.WorkspaceKataMetadata{
			DaemonID: "home", ProjectUID: "project-1", ProjectName: "Widget",
			IssueUID: "issue-kata-1", ShortID: "KAT-12", Title: "Wire task context",
		},
	}))

	launch := func(workspaceID string) {
		t.Helper()
		req := httptest.NewRequest(
			http.MethodPost,
			"/api/v1/workspaces/"+workspaceID+"/runtime/sessions",
			bytes.NewBufferString(`{"target_key":"codex"}`),
		)
		req.Header.Set("Content-Type", "application/json")
		rec := httptest.NewRecorder()
		srv.ServeHTTP(rec, req)
		require.Equal(http.StatusOK, rec.Code, rec.Body.String())
	}

	launch("ws-issue-context")
	issueContext, err := os.ReadFile(filepath.Join(issueWorktree, "AGENTS.local.md"))
	require.NoError(err)
	assert.Contains(string(issueContext), "Source kind: provider issue")
	assert.Contains(string(issueContext), "Issue: #7")
	assert.Contains(string(issueContext), "https://github.com/acme/widget/issues/7")
	assert.Contains(string(issueContext), "<untrusted-source-text>Test Issue</untrusted-source-text>")
	issueStatus := strings.TrimSpace(string(runServerWorkspaceTestGit(t, issueWorktree, "status", "--porcelain")))
	assert.Empty(issueStatus)

	// A pre-existing user-owned file makes launch succeed without touching
	// it: context delivery is silently skipped by design.
	userOwned := "# My own instructions\n"
	require.NoError(os.WriteFile(filepath.Join(kataWorktree, "AGENTS.local.md"), []byte(userOwned), 0o644))
	launch("ws-kata-context")
	preserved, err := os.ReadFile(filepath.Join(kataWorktree, "AGENTS.local.md"))
	require.NoError(err)
	require.Equal(userOwned, string(preserved))
	require.NoError(os.Remove(filepath.Join(kataWorktree, "AGENTS.local.md")))

	launch("ws-kata-context")
	kataContext, err := os.ReadFile(filepath.Join(kataWorktree, "AGENTS.local.md"))
	require.NoError(err)
	assert.Contains(string(kataContext), "Source kind: Kata task")
	assert.Contains(string(kataContext), "Kata daemon: home")
	assert.Contains(string(kataContext), "Issue UID: issue-kata-1")
	assert.Contains(string(kataContext), "Short ID: KAT-12")
	assert.Contains(string(kataContext), "<untrusted-source-text>Wire task context</untrusted-source-text>")
	kataStatus := strings.TrimSpace(string(runServerWorkspaceTestGit(t, kataWorktree, "status", "--porcelain")))
	assert.Empty(kataStatus)
}

func seedServerWorkspaceRepo(t *testing.T, d *db.DB) int64 {
	t.Helper()
	repoID, err := d.UpsertRepo(t.Context(), db.GitHubRepoIdentity("github.com", "acme", "widget"))
	require.NoError(t, err)
	return repoID
}

func seedServerWorkspaceMR(t *testing.T, d *db.DB, repoID int64) {
	t.Helper()
	now := time.Date(2024, 6, 1, 12, 0, 0, 0, time.UTC)
	_, err := d.UpsertMergeRequest(t.Context(), &db.MergeRequest{
		RepoID:         repoID,
		PlatformID:     4200,
		Number:         42,
		URL:            "https://github.com/acme/widget/pull/42",
		Title:          "Launch context",
		Author:         "author",
		State:          "open",
		HeadBranch:     "feature/widgets",
		BaseBranch:     "main",
		CreatedAt:      now,
		UpdatedAt:      now,
		LastActivityAt: now,
	})
	require.NoError(t, err)
}

func initServerWorkspaceGitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	runServerWorkspaceTestGit(t, dir, "init", "--initial-branch=main")
	runServerWorkspaceTestGit(t, dir, "config", "user.email", "test@example.test")
	runServerWorkspaceTestGit(t, dir, "config", "user.name", "Test User")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "README.md"), []byte("# Test\n"), 0o644))
	runServerWorkspaceTestGit(t, dir, "add", "README.md")
	runServerWorkspaceTestGit(t, dir, "commit", "-m", "initial")
	return dir
}

func runServerWorkspaceTestGit(t *testing.T, dir string, args ...string) []byte {
	t.Helper()
	out, stderr, err := gitcmd.New().Run(t.Context(), dir, nil, args...)
	require.NoError(t, err, "git %v failed: %s%s", args, out, stderr)
	return out
}

func assertServerGitIgnored(t *testing.T, dir, rel string) {
	t.Helper()
	runServerWorkspaceTestGit(t, dir, "check-ignore", "--quiet", "--", rel)
}
