import { describe, expect, it } from "vite-plus/test";
import { commitAttribution } from "./commit-attribution.js";

describe("commitAttribution", () => {
  it.each([
    ["Generated with Codex", "Codex"],
    ["Generated with Codex (GPT-5)", "Codex"],
    ["<sup>Generated with Codex</sup>", "Codex"],
    ["\u{1f916} Generated with [OpenAI Codex](https://openai.com/codex)", "Codex"],
    ["\u{1f916} Generated with [Claude Code](https://claude.com/claude-code)", "Claude Code"],
    ["Generated with Claude Code (claude-fable-5)", "Claude Code"],
    ["Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>", "Claude Code"],
    ["Co-authored-by: OpenAI Codex <codex@openai.com>", "Codex"],
    ["Co-authored-by: Pi <noreply@openai.com>", "Pi"],
    ["Co-authored-by: Pi <pi@earendil.works>", "Pi"],
    ["Generated with Pi", "Pi"],
    ["Generated with Grok (4.7)", "Grok"],
    ["Co-authored-by: Grok <noreply@x.ai>", "Grok"],
  ])("extracts %s", (line, name) => {
    const result = commitAttribution(`fix: preserve selection\r\n\r\nKeep the selection.\r\n\r\n${line}`);
    expect(result.message).toBe("fix: preserve selection\n\nKeep the selection.");
    expect(result.agents.map((agent) => agent.name)).toEqual([name]);
  });

  it("deduplicates attribution pairs and retains multiple agents and human co-authors", () => {
    const result = commitAttribution(
      [
        "fix: preserve selection",
        "",
        "Generated with Codex",
        "Co-authored-by: Codex <noreply@openai.com>",
        "Generated with Pi",
        "Co-authored-by: Pi <noreply@openai.com>",
        "Co-authored-by: Alex Morgan <alex@example.com>",
      ].join("\n"),
    );
    expect(result.agents).toEqual([
      { harness: "openai", name: "Codex" },
      { harness: "pi", name: "Pi" },
    ]);
    expect(result.message).toBe("fix: preserve selection\n\nCo-authored-by: Alex Morgan <alex@example.com>");
  });

  it("preserves subjects, prose, unknown attribution, escaped text, and fenced examples", () => {
    const message = [
      "Generated with Codex",
      "",
      "Explain Generated with Codex in the documentation.",
      "Generated with an unknown tool",
      "<sup>generated by a clanker</sup>",
      "Generated with Codex\\nCo-authored-by: Codex <noreply@openai.com>",
      "```text",
      "Generated with Codex",
      "```",
      "~~~",
      "Co-authored-by: Pi <noreply@openai.com>",
      "~~~",
    ].join("\n");
    expect(commitAttribution(message)).toEqual({ message, agents: [] });
  });
});
