DROP TRIGGER IF EXISTS forge_issue_events_activity_revision_delete;
DROP TRIGGER IF EXISTS forge_issue_events_activity_revision_update;
DROP TRIGGER IF EXISTS forge_issue_events_activity_revision_insert;
DROP TRIGGER IF EXISTS forge_mr_events_activity_revision_delete;
DROP TRIGGER IF EXISTS forge_mr_events_activity_revision_update;
DROP TRIGGER IF EXISTS forge_mr_events_activity_revision_insert;

DROP INDEX IF EXISTS idx_forge_notification_items_activity_parent;

ALTER TABLE forge_issues DROP COLUMN activity_event_revision;
ALTER TABLE forge_merge_requests DROP COLUMN activity_event_revision;
