// Code generated by oapi-codegen. DO NOT EDIT.

package health

import (
	"context"
	"encoding/json/v2"
	"fmt"
	"net/http"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// Client is the client for the API implementing the ClientInterface interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client. With
// envelope-only generation it lists the WithResponse methods.
type ClientInterface interface {
	GetHealthzWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetHealthzResp, error)
	GetLivezWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetLivezResp, error)
}

// GetHealthz Get healthz
func (c *Client) GetHealthzWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetHealthzResp, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/healthz",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/healthz")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetHealthzResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(GetHealthzErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetHealthzResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetHealthzResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetLivez Get livez
func (c *Client) GetLivezWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetLivezResp, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/livez",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/livez")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetLivezResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(GetLivezErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetLivezResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetLivezResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

var _ ClientInterface = (*Client)(nil)

// GetHealthzRaw returns an unread response. The caller must close its body.
func (c *Client) GetHealthzRaw(ctx context.Context, httpClient *http.Client, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/healthz",
		Method:     "GET",
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// GetLivezRaw returns an unread response. The caller must close its body.
func (c *Client) GetLivezRaw(ctx context.Context, httpClient *http.Client, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/livez",
		Method:     "GET",
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// NewGetHealthzRequest constructs a typed request for a caller-owned transport.
func NewGetHealthzRequest(ctx context.Context, baseURL string, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/healthz",
		Method:     "GET",
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

// NewGetLivezRequest constructs a typed request for a caller-owned transport.
func NewGetLivezRequest(ctx context.Context, baseURL string, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/livez",
		Method:     "GET",
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

// ProblemErrorCode Machine-readable error code. Stable across occurrences.
type ProblemErrorCode string

const (
	BadRequest                    ProblemErrorCode = "badRequest"
	BranchConflict                ProblemErrorCode = "branchConflict"
	BranchInUse                   ProblemErrorCode = "branchInUse"
	BranchProtected               ProblemErrorCode = "branchProtected"
	CommentNotFound               ProblemErrorCode = "commentNotFound"
	Conflict                      ProblemErrorCode = "conflict"
	DestinationExists             ProblemErrorCode = "destinationExists"
	Forbidden                     ProblemErrorCode = "forbidden"
	GitCredentialUnavailable      ProblemErrorCode = "gitCredentialUnavailable"
	HookFailed                    ProblemErrorCode = "hookFailed"
	HubUnavailable                ProblemErrorCode = "hubUnavailable"
	InternalError                 ProblemErrorCode = "internalError"
	IssueNotFound                 ProblemErrorCode = "issueNotFound"
	MutationOutcomeUnknown        ProblemErrorCode = "mutationOutcomeUnknown"
	NotFound                      ProblemErrorCode = "notFound"
	PayloadTooLarge               ProblemErrorCode = "payloadTooLarge"
	ProjectNotFound               ProblemErrorCode = "projectNotFound"
	PullNotFound                  ProblemErrorCode = "pullNotFound"
	RateLimited                   ProblemErrorCode = "rateLimited"
	RepoNotFound                  ProblemErrorCode = "repoNotFound"
	ResyncRequired                ProblemErrorCode = "resyncRequired"
	ServiceUnavailable            ProblemErrorCode = "serviceUnavailable"
	SettingsUnavailable           ProblemErrorCode = "settingsUnavailable"
	SpokePreparationInProgress    ProblemErrorCode = "spokePreparationInProgress"
	ToolMissing                   ProblemErrorCode = "toolMissing"
	ToolUnauthenticated           ProblemErrorCode = "toolUnauthenticated"
	Unauthorized                  ProblemErrorCode = "unauthorized"
	UnsupportedCapability         ProblemErrorCode = "unsupportedCapability"
	UpstreamError                 ProblemErrorCode = "upstreamError"
	ValidationError               ProblemErrorCode = "validationError"
	WorkspaceAlreadyExists        ProblemErrorCode = "workspaceAlreadyExists"
	WorkspaceDeletionInProgress   ProblemErrorCode = "workspaceDeletionInProgress"
	WorkspaceDirectoryNotReusable ProblemErrorCode = "workspaceDirectoryNotReusable"
	WorkspaceNotFound             ProblemErrorCode = "workspaceNotFound"
	WorkspaceSetupInProgress      ProblemErrorCode = "workspaceSetupInProgress"
	WorktreeDirty                 ProblemErrorCode = "worktreeDirty"
)

type GetHealthzResponse = HealthResponse

type GetHealthzErrorResponse = ProblemError

type GetLivezResponse = HealthResponse

type GetLivezErrorResponse = ProblemError

type GetHealthzResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *GetHealthzErrorResponse
	JSON200      *GetHealthzResponse
}

type GetLivezResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *GetLivezErrorResponse
	JSON200      *GetLivezResponse
}

type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value *struct{} `json:"value,omitempty"`
}

type HealthResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Status string  `json:"status"`
}

type ProblemError struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Code Machine-readable error code. Stable across occurrences.
	Code ProblemErrorCode `json:"code"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Details Machine-readable error context, keyed by code-specific conventions.
	Details map[string]struct{} `json:"details,omitempty"`

	// Errors Optional list of individual error details
	Errors []ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

func (s ProblemError) Error() string {
	return "unmapped client error"
}
