// Code generated by oapi-codegen. DO NOT EDIT.

package devbox

import (
	"context"
	"encoding/json/v2"
	"fmt"
	"net/http"
	"net/url"
	"time"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// PostAPIV1DevboxesByHostIDConnectRequestOptions is the options needed to make a request to PostAPIV1DevboxesByHostIDConnect.
type PostAPIV1DevboxesByHostIDConnectRequestOptions struct {
	PathParams *PostAPIV1DevboxesByHostIDConnectPath
}

// GetPathParams returns the path params as a map.
func (o *PostAPIV1DevboxesByHostIDConnectRequestOptions) GetPathParams() (map[string]any, error) {
	params, err := runtime.AsMap[any](o.PathParams)
	if err != nil {
		return nil, err
	}
	for key, value := range params {
		params[key] = url.PathEscape(fmt.Sprint(value))
	}
	return params, nil
}

// GetQuery returns the query params as a map.
func (o *PostAPIV1DevboxesByHostIDConnectRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *PostAPIV1DevboxesByHostIDConnectRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *PostAPIV1DevboxesByHostIDConnectRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// EraseDevboxCredentialRequestOptions is the options needed to make a request to EraseDevboxCredential.
type EraseDevboxCredentialRequestOptions struct {
	Query *EraseDevboxCredentialQuery
}

// GetPathParams returns the path params as a map.
func (o *EraseDevboxCredentialRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *EraseDevboxCredentialRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *EraseDevboxCredentialRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *EraseDevboxCredentialRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// DevboxCredentialRequestOptions is the options needed to make a request to DevboxCredential.
type DevboxCredentialRequestOptions struct {
	Body *DevboxCredentialBody
}

// GetPathParams returns the path params as a map.
func (o *DevboxCredentialRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *DevboxCredentialRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *DevboxCredentialRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *DevboxCredentialRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// Client is the client for the API implementing the ClientInterface interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client. With
// envelope-only generation it lists the WithResponse methods.
type ClientInterface interface {
	GetAPIV1DevboxesWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetAPIV1DevboxesResp, error)
	PostAPIV1DevboxesByHostIDConnectWithResponse(ctx context.Context, options *PostAPIV1DevboxesByHostIDConnectRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PostAPIV1DevboxesByHostIDConnectResp, error)
	GetHealthzWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetHealthzResp, error)
	EraseDevboxCredentialWithResponse(ctx context.Context, options *EraseDevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*EraseDevboxCredentialResp, error)
	DevboxCredentialWithResponse(ctx context.Context, options *DevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*DevboxCredentialResp, error)
}

// GetAPIV1Devboxes Get API v1 devboxes
func (c *Client) GetAPIV1DevboxesWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetAPIV1DevboxesResp, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/devboxes",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/devboxes")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetAPIV1DevboxesResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(GetAPIV1DevboxesErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetAPIV1DevboxesResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetAPIV1DevboxesResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// PostAPIV1DevboxesByHostIDConnect Post API v1 devboxes by host ID connect
func (c *Client) PostAPIV1DevboxesByHostIDConnectWithResponse(ctx context.Context, options *PostAPIV1DevboxesByHostIDConnectRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PostAPIV1DevboxesByHostIDConnectResp, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/devboxes/{host_id}/connect",
		Method:     "POST",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/devboxes/{host_id}/connect")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &PostAPIV1DevboxesByHostIDConnectResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(PostAPIV1DevboxesByHostIDConnectErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(PostAPIV1DevboxesByHostIDConnectResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "PostAPIV1DevboxesByHostIDConnectResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetHealthz Get healthz
func (c *Client) GetHealthzWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*GetHealthzResp, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/healthz",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/healthz")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetHealthzResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(GetHealthzErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetHealthzResponseJSON)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetHealthzResponseJSON",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

func (c *Client) EraseDevboxCredentialWithResponse(ctx context.Context, options *EraseDevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*EraseDevboxCredentialResp, error) {
	var err error

	queryEncoding := map[string]runtime.QueryEncoding{
		"repository": {Style: "form", Explode: &[]bool{false}[0]},
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/v1/credentials",
		Method:        "DELETE",
		Options:       options,
		QueryEncoding: queryEncoding,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/v1/credentials")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &EraseDevboxCredentialResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(EraseDevboxCredentialErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 204:
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

func (c *Client) DevboxCredentialWithResponse(ctx context.Context, options *DevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*DevboxCredentialResp, error) {
	var err error

	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/v1/credentials",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/v1/credentials")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &DevboxCredentialResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(DevboxCredentialErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(DevboxCredentialResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "DevboxCredentialResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

var _ ClientInterface = (*Client)(nil)

// GetAPIV1DevboxesRaw returns an unread response. The caller must close its body.
func (c *Client) GetAPIV1DevboxesRaw(ctx context.Context, httpClient *http.Client, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/devboxes",
		Method:     "GET",
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// PostAPIV1DevboxesByHostIDConnectRaw returns an unread response. The caller must close its body.
func (c *Client) PostAPIV1DevboxesByHostIDConnectRaw(ctx context.Context, httpClient *http.Client, options *PostAPIV1DevboxesByHostIDConnectRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/devboxes/{host_id}/connect",
		Method:     "POST",
		Options:    options,
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// GetHealthzRaw returns an unread response. The caller must close its body.
func (c *Client) GetHealthzRaw(ctx context.Context, httpClient *http.Client, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/healthz",
		Method:     "GET",
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// EraseDevboxCredentialRaw returns an unread response. The caller must close its body.
func (c *Client) EraseDevboxCredentialRaw(ctx context.Context, httpClient *http.Client, options *EraseDevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	queryEncoding := map[string]runtime.QueryEncoding{
		"repository": {Style: "form", Explode: &[]bool{false}[0]},
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/v1/credentials",
		Method:        "DELETE",
		Options:       options,
		QueryEncoding: queryEncoding,
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// DevboxCredentialRaw returns an unread response. The caller must close its body.
func (c *Client) DevboxCredentialRaw(ctx context.Context, httpClient *http.Client, options *DevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/v1/credentials",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// NewGetAPIV1DevboxesRequest constructs a typed request for a caller-owned transport.
func NewGetAPIV1DevboxesRequest(ctx context.Context, baseURL string, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/devboxes",
		Method:     "GET",
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

// NewPostAPIV1DevboxesByHostIDConnectRequest constructs a typed request for a caller-owned transport.
func NewPostAPIV1DevboxesByHostIDConnectRequest(ctx context.Context, baseURL string, options *PostAPIV1DevboxesByHostIDConnectRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/devboxes/{host_id}/connect",
		Method:     "POST",
		Options:    options,
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

// NewGetHealthzRequest constructs a typed request for a caller-owned transport.
func NewGetHealthzRequest(ctx context.Context, baseURL string, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/healthz",
		Method:     "GET",
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

// NewEraseDevboxCredentialRequest constructs a typed request for a caller-owned transport.
func NewEraseDevboxCredentialRequest(ctx context.Context, baseURL string, options *EraseDevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	queryEncoding := map[string]runtime.QueryEncoding{
		"repository": {Style: "form", Explode: &[]bool{false}[0]},
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/v1/credentials",
		Method:        "DELETE",
		Options:       options,
		QueryEncoding: queryEncoding,
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

// NewDevboxCredentialRequest constructs a typed request for a caller-owned transport.
func NewDevboxCredentialRequest(ctx context.Context, baseURL string, options *DevboxCredentialRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/v1/credentials",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

type CredentialRequestProfile string

const (
	Git  CredentialRequestProfile = "git"
	Pr   CredentialRequestProfile = "pr"
	Push CredentialRequestProfile = "push"
)

// ProblemErrorCode Machine-readable error code. Stable across occurrences.
type ProblemErrorCode string

const (
	BadRequest                    ProblemErrorCode = "badRequest"
	BranchConflict                ProblemErrorCode = "branchConflict"
	BranchInUse                   ProblemErrorCode = "branchInUse"
	BranchProtected               ProblemErrorCode = "branchProtected"
	CommentNotFound               ProblemErrorCode = "commentNotFound"
	Conflict                      ProblemErrorCode = "conflict"
	DestinationExists             ProblemErrorCode = "destinationExists"
	Forbidden                     ProblemErrorCode = "forbidden"
	GitCredentialUnavailable      ProblemErrorCode = "gitCredentialUnavailable"
	HookFailed                    ProblemErrorCode = "hookFailed"
	HubUnavailable                ProblemErrorCode = "hubUnavailable"
	InternalError                 ProblemErrorCode = "internalError"
	IssueNotFound                 ProblemErrorCode = "issueNotFound"
	MutationOutcomeUnknown        ProblemErrorCode = "mutationOutcomeUnknown"
	NotFound                      ProblemErrorCode = "notFound"
	PayloadTooLarge               ProblemErrorCode = "payloadTooLarge"
	ProjectNotFound               ProblemErrorCode = "projectNotFound"
	PullNotFound                  ProblemErrorCode = "pullNotFound"
	RateLimited                   ProblemErrorCode = "rateLimited"
	RepoNotFound                  ProblemErrorCode = "repoNotFound"
	ResyncRequired                ProblemErrorCode = "resyncRequired"
	ServiceUnavailable            ProblemErrorCode = "serviceUnavailable"
	SettingsUnavailable           ProblemErrorCode = "settingsUnavailable"
	SpokePreparationInProgress    ProblemErrorCode = "spokePreparationInProgress"
	ToolMissing                   ProblemErrorCode = "toolMissing"
	ToolUnauthenticated           ProblemErrorCode = "toolUnauthenticated"
	Unauthorized                  ProblemErrorCode = "unauthorized"
	UnsupportedCapability         ProblemErrorCode = "unsupportedCapability"
	UpstreamError                 ProblemErrorCode = "upstreamError"
	ValidationError               ProblemErrorCode = "validationError"
	WorkspaceAlreadyExists        ProblemErrorCode = "workspaceAlreadyExists"
	WorkspaceDeletionInProgress   ProblemErrorCode = "workspaceDeletionInProgress"
	WorkspaceDirectoryNotReusable ProblemErrorCode = "workspaceDirectoryNotReusable"
	WorkspaceNotFound             ProblemErrorCode = "workspaceNotFound"
	WorkspaceSetupInProgress      ProblemErrorCode = "workspaceSetupInProgress"
	WorktreeDirty                 ProblemErrorCode = "worktreeDirty"
)

type PostAPIV1DevboxesByHostIDConnectPath struct {
	HostID string `json:"host_id"`
}

type DevboxCredentialBody = CredentialRequest

type EraseDevboxCredentialQuery struct {
	Repository string `json:"repository"`
}

type GetAPIV1DevboxesResponse = Discovery

type GetAPIV1DevboxesErrorResponse = ProblemError

type PostAPIV1DevboxesByHostIDConnectResponse = Profile

type PostAPIV1DevboxesByHostIDConnectErrorResponse = ProblemError

type GetHealthzResponseJSON = GetHealthzResponse

type GetHealthzErrorResponse = ProblemError

type EraseDevboxCredentialErrorResponse = ProblemError

type DevboxCredentialResponse = Credential

type DevboxCredentialErrorResponse = ProblemError

type GetAPIV1DevboxesResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *GetAPIV1DevboxesErrorResponse
	JSON200      *GetAPIV1DevboxesResponse
}

type PostAPIV1DevboxesByHostIDConnectResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *PostAPIV1DevboxesByHostIDConnectErrorResponse
	JSON200      *PostAPIV1DevboxesByHostIDConnectResponse
}

type GetHealthzResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *GetHealthzErrorResponse
	JSON200      *GetHealthzResponseJSON
}

type EraseDevboxCredentialResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *EraseDevboxCredentialErrorResponse
}

type DevboxCredentialResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *DevboxCredentialErrorResponse
	JSON200      *DevboxCredentialResponse
}

type Assignment struct {
	Account            string `json:"account"`
	GithubUserID       int64  `json:"github_user_id"`
	HostID             string `json:"host_id"`
	Maintenance        bool   `json:"maintenance"`
	Name               string `json:"name"`
	NodeID             string `json:"node_id"`
	Protocol           int64  `json:"protocol"`
	Role               string `json:"role"`
	SSHAddress         string `json:"ssh_address"`
	SSHHostFingerprint string `json:"ssh_host_fingerprint"`
	UID                int32  `json:"uid"`
	URL                string `json:"url"`
}

type Credential struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string   `json:"$schema,omitempty"`
	DefaultBranch string    `json:"default_branch"`
	ExpiresAt     time.Time `json:"expires_at"`
	GithubUserID  int64     `json:"github_user_id"`
	RepositoryID  int64     `json:"repository_id"`
	Token         string    `json:"token"`
	Writable      bool      `json:"writable"`
}

type CredentialRequest struct {
	// Schema A URL to the JSON Schema for this object.
	Schema  *string                  `json:"$schema,omitempty"`
	Profile CredentialRequestProfile `json:"profile"`

	// Repository GitHub owner/name
	Repository string `json:"repository"`
}

type Discovery struct {
	// Schema A URL to the JSON Schema for this object.
	Schema       *string      `json:"$schema,omitempty"`
	Devboxes     []Assignment `json:"devboxes"`
	GithubUserID int64        `json:"github_user_id"`
	Protocol     int64        `json:"protocol"`
	RegistryID   string       `json:"registry_id"`
	RegistryURL  *string      `json:"registry_url,omitempty"`
	Revision     string       `json:"revision"`
}

type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value *struct{} `json:"value,omitempty"`
}

type GetHealthzResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Status string  `json:"status"`
}

type ProblemError struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Code Machine-readable error code. Stable across occurrences.
	Code ProblemErrorCode `json:"code"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Details Machine-readable error context, keyed by code-specific conventions.
	Details map[string]struct{} `json:"details,omitempty"`

	// Errors Optional list of individual error details
	Errors []ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

func (s ProblemError) Error() string {
	return "unmapped client error"
}

type Profile struct {
	// Schema A URL to the JSON Schema for this object.
	Schema             *string `json:"$schema,omitempty"`
	Account            string  `json:"account"`
	GithubUserID       int64   `json:"github_user_id"`
	HostID             string  `json:"host_id"`
	Maintenance        bool    `json:"maintenance"`
	Name               string  `json:"name"`
	NodeID             string  `json:"node_id"`
	Protocol           int64   `json:"protocol"`
	RegistryID         string  `json:"registry_id"`
	Revision           string  `json:"revision"`
	Role               string  `json:"role"`
	SSHAddress         string  `json:"ssh_address"`
	SSHHostFingerprint string  `json:"ssh_host_fingerprint"`
	Token              string  `json:"token"`
	UID                int32   `json:"uid"`
	URL                string  `json:"url"`
}
