// Code generated by oapi-codegen. DO NOT EDIT.

package roborev

import (
	"context"
	"encoding/json/v2"
	"fmt"
	"net/http"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// ListReposRequestOptions is the options needed to make a request to ListRepos.
type ListReposRequestOptions struct {
	Query *ListReposQuery
}

// GetPathParams returns the path params as a map.
func (o *ListReposRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *ListReposRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ListReposRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ListReposRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// Client is the client for the API implementing the ClientInterface interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client. With
// envelope-only generation it lists the WithResponse methods.
type ClientInterface interface {
	ListReposWithResponse(ctx context.Context, options *ListReposRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListReposResp, error)
}

// ListRepos List repos with job counts
func (c *Client) ListReposWithResponse(ctx context.Context, options *ListReposRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListReposResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/repos",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/repos")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &ListReposResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}
	if resp.StatusCode >= 400 && len(resp.Content) > 0 {
		problem := new(ListReposErrorResponse)
		if err := json.Unmarshal(resp.Content, problem); err != nil {
			return out, fmt.Errorf("decode API error response: %w", err)
		}
		out.Error = problem
	}
	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(ListReposResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "ListReposResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	case 500:
		return out, runtime.NewClientAPIError(fmt.Errorf("API error (status %d)", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

var _ ClientInterface = (*Client)(nil)

// ListReposRaw returns an unread response. The caller must close its body.
func (c *Client) ListReposRaw(ctx context.Context, httpClient *http.Client, options *ListReposRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Response, error) {

	queryEncoding := map[string]runtime.QueryEncoding{
		"branch": {Style: "form", Explode: &[]bool{false}[0]},
		"prefix": {Style: "form", Explode: &[]bool{false}[0]},
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/api/repos",
		Method:        "GET",
		Options:       options,
		QueryEncoding: queryEncoding,
	}
	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// NewListReposRequest constructs a typed request for a caller-owned transport.
func NewListReposRequest(ctx context.Context, baseURL string, options *ListReposRequestOptions, reqEditors ...runtime.RequestEditorFn) (*http.Request, error) {
	apiClient, err := runtime.NewAPIClient(baseURL)
	if err != nil {
		return nil, err
	}
	c := NewClient(apiClient)

	queryEncoding := map[string]runtime.QueryEncoding{
		"branch": {Style: "form", Explode: &[]bool{false}[0]},
		"prefix": {Style: "form", Explode: &[]bool{false}[0]},
	}
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:    c.apiClient.GetBaseURL() + "/api/repos",
		Method:        "GET",
		Options:       options,
		QueryEncoding: queryEncoding,
	}
	return apiClient.CreateRequest(ctx, reqParams, reqEditors...)
}

type ListReposQuery struct {
	// Branch Filter to repos with jobs on this branch
	Branch *string `json:"branch,omitempty"`

	// Prefix Filter repos by path prefix
	Prefix *string `json:"prefix,omitempty"`
}

type ListReposResponse = ListReposOutputBody

type ListReposErrorResponse = ErrorModel

type ListReposResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	Error        *ListReposErrorResponse
	JSON200      *ListReposResponse
}

type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value *struct{} `json:"value,omitempty"`
}

type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors []ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

func (s ErrorModel) Error() string {
	return "unmapped client error"
}

type ListReposOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string         `json:"$schema,omitempty"`
	Repos      []RepoWithCount `json:"repos,omitempty"`
	TotalCount int64           `json:"total_count"`
}

type RepoWithCount struct {
	Count    int64   `json:"count"`
	Identity *string `json:"identity,omitempty"`
	Name     string  `json:"name"`
	RootPath string  `json:"root_path"`
}
