package runtimetest

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.kenn.io/forge/internal/db"
	"go.kenn.io/forge/internal/server/workspaceapi"
	"go.kenn.io/forge/internal/testutil/dbtest"
	serverfake "go.kenn.io/forge/internal/testutil/serverfake"
	"go.kenn.io/forge/internal/workspace"
	"go.kenn.io/forge/internal/workspace/localruntime"

	gitcmd "go.kenn.io/kit/git/cmd"
)

func TestLaunchWorkspaceRuntimeSessionPreparesAgentContext(t *testing.T) {
	serverfake.RunParallelServerTest(t)
	serverfake.AcquireRootWorkspaceGitSlot(t)
	assert := assert.New(t)
	require := require.New(t)
	d := dbtest.Open(t)
	worktree := initServerWorkspaceGitRepo(t)
	repoID := seedServerWorkspaceRepo(t, d)
	seedServerWorkspaceMR(t, d, repoID)

	ws := &db.Workspace{
		ID:              "ws-agent-context",
		Platform:        "github",
		PlatformHost:    "github.com",
		RepoOwner:       "acme",
		RepoName:        "widget",
		ItemType:        db.WorkspaceItemTypePullRequest,
		ItemNumber:      42,
		GitHeadRef:      "feature/widgets",
		WorkspaceBranch: "feature/widgets",
		WorktreePath:    worktree,
		TmuxSession:     "kenn-forge-ws-agent-context",
		TerminalBackend: "tmux",
		Status:          "ready",
	}
	require.NoError(d.InsertWorkspace(t.Context(), ws))
	seedServerWorkspaceLaunchSpec(t, d, ws, repoID)
	require.NoError(os.WriteFile(
		filepath.Join(worktree, "AGENTS.md"),
		[]byte("# Repository Agent Rules\n\nKeep this guidance.\n"), 0o644,
	))
	runServerWorkspaceTestGit(t, worktree, "add", "AGENTS.md")
	runServerWorkspaceTestGit(t, worktree, "commit", "-m", "add agent rules")
	staleMarked := "<!-- generated by kenn-forge; safe to delete; regenerated on agent launch -->\nstale\n"
	require.NoError(os.WriteFile(filepath.Join(worktree, "AGENTS.override.md"), []byte(staleMarked), 0o644))

	tmuxPath := writeRuntimeTmuxLifecycleRecorder(t, t.TempDir(), filepath.Join(t.TempDir(), "tmux-record"))
	runtime := localruntime.NewManager(localruntime.Options{
		Targets: []localruntime.LaunchTarget{
			{
				Key:       "Codex yolo",
				Label:     "Codex",
				Kind:      localruntime.LaunchTargetAgent,
				Command:   []string{"/bin/sh", "-c", "exit 0"},
				Available: true,
			},
			{
				Key:       string(localruntime.LaunchTargetShell),
				Label:     "tmux",
				Kind:      localruntime.LaunchTargetShell,
				Command:   []string{tmuxPath},
				Available: true,
			},
		},
		TmuxCommand:             []string{tmuxPath},
		WrapAgentSessionsInTmux: true,
	})
	handler := workspaceapi.New(workspaceapi.Deps{
		DB:         d,
		Workspaces: workspace.NewManager(d, t.TempDir()),
		Runtime:    runtime,
	})
	input := &workspaceapi.LaunchWorkspaceRuntimeSessionInput{ID: ws.ID}
	input.Body.TargetKey = "Codex yolo"

	_, err := handler.LaunchWorkspaceRuntimeSession(t.Context(), input)
	require.NoError(err)

	override, err := os.ReadFile(filepath.Join(worktree, "AGENTS.override.md"))
	require.NoError(err)
	content := string(override)
	assert.Contains(content, "Source kind: pull request")
	assert.Contains(content, "PR: #42")
	assert.Contains(content, "Push branch: feature/widgets")
	assert.NotContains(content, "stale")
	assert.Less(
		strings.Index(content, "# Kenn Forge Workspace Context"),
		strings.Index(content, "# Repository Agent Rules"),
	)
	assert.True(strings.HasSuffix(content, "# Repository Agent Rules\n\nKeep this guidance.\n"))
	assert.NoFileExists(filepath.Join(worktree, "CLAUDE.local.md"))
	assertServerGitIgnored(t, worktree, "AGENTS.override.md")
	status := strings.TrimSpace(string(runServerWorkspaceTestGit(t, worktree, "status", "--porcelain")))
	assert.Empty(status)
}

func seedServerWorkspaceRepo(t *testing.T, d *db.DB) int64 {
	t.Helper()
	repoID, err := d.UpsertRepo(t.Context(), serverfake.VerifiedGitHubRepoIdentity("github.com", "acme", "widget"))
	require.NoError(t, err)
	serverfake.SeedRepoLaunchMetadata(t, d, repoID)
	return repoID
}

func seedServerWorkspaceLaunchSpec(
	t *testing.T, database *db.DB, ws *db.Workspace, repoID int64,
) {
	t.Helper()
	repo, err := database.GetRepoByID(t.Context(), repoID)
	require.NoError(t, err)
	require.NotNil(t, repo)
	issuedAt := time.Now().UTC()
	spec := db.WorkspaceLaunchSpec{
		Version: db.WorkspaceLaunchSpecVersion,
		Repository: db.WorkspaceLaunchRepository{
			Provider: repo.Platform, PlatformHost: repo.PlatformHost,
			PlatformRepoID: repo.PlatformRepoID, Owner: repo.Owner, Name: repo.Name,
			CloneURL: repo.CloneURL, DefaultBranch: repo.DefaultBranch,
		},
		ItemType: ws.ItemType, ItemNumber: ws.ItemNumber,
		ItemKey: strconv.Itoa(ws.ItemNumber), GitHeadRef: ws.GitHeadRef,
		SourceVisible: true, IssuedAt: issuedAt,
		SourceVisibleUntil: issuedAt.Add(db.WorkspaceLaunchSpecVisibilityLease),
	}
	if ws.ItemType == db.WorkspaceItemTypePullRequest {
		pull, readErr := database.GetMergeRequestByRepoIDAndNumber(
			t.Context(), repoID, ws.ItemNumber,
		)
		require.NoError(t, readErr)
		require.NotNil(t, pull)
		spec.Pull = &db.WorkspaceLaunchPull{
			HeadBranch: pull.HeadBranch, HeadRepoKind: "same_repo",
			SnapshotRevision: pull.SnapshotRevision,
		}
	}
	require.NoError(t, database.PutWorkspaceLaunchSpec(t.Context(), ws.ID, spec))
}

func seedServerWorkspaceMR(t *testing.T, d *db.DB, repoID int64) {
	t.Helper()
	now := time.Date(2024, 6, 1, 12, 0, 0, 0, time.UTC)
	_, err := d.UpsertMergeRequest(t.Context(), &db.MergeRequest{
		RepoID:         repoID,
		PlatformID:     4200,
		Number:         42,
		URL:            "https://github.com/acme/widget/pull/42",
		Title:          "Launch context",
		Author:         "author",
		State:          "open",
		HeadBranch:     "feature/widgets",
		BaseBranch:     "main",
		CreatedAt:      now,
		UpdatedAt:      now,
		LastActivityAt: now,
	})
	require.NoError(t, err)
}

func initServerWorkspaceGitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	runServerWorkspaceTestGit(t, dir, "init", "--initial-branch=main")
	runServerWorkspaceTestGit(t, dir, "config", "user.email", "test@example.test")
	runServerWorkspaceTestGit(t, dir, "config", "user.name", "Test User")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "README.md"), []byte("# Test\n"), 0o644))
	runServerWorkspaceTestGit(t, dir, "add", "README.md")
	runServerWorkspaceTestGit(t, dir, "commit", "-m", "initial")
	return dir
}

func runServerWorkspaceTestGit(t *testing.T, dir string, args ...string) []byte {
	t.Helper()
	out, stderr, err := gitcmd.New().Run(t.Context(), dir, nil, args...)
	require.NoError(t, err, "git %v failed: %s%s", args, out, stderr)
	return out
}

func assertServerGitIgnored(t *testing.T, dir, rel string) {
	t.Helper()
	runServerWorkspaceTestGit(t, dir, "check-ignore", "--quiet", "--", rel)
}
